version: "3"

services:
  keycloak:
    environment:
      - KEYCLOAK_IMPORT=/config/e2e-divoc-realm.json
    volumes:
      - ./keycloak:/config
  portal_api:
    environment:
      ADMIN_API_CLIENT_SECRET: a1832880-059a-40d0-86b1-e318ced82613
  certificate_processor:
      environment:
        ADMIN_API_CLIENT_SECRET: a1832880-059a-40d0-86b1-e318ced82613
