apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-komp.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-komp.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: DB_ADDR
              value: --
            - name: DB_DATABASE
              value: --
            - name: DB_PASSWORD
              value: --
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
          image: bindock/keycloak:TAG
          name: keycloak
          ports:
            - containerPort: 8080
            - containerPort: 9990
          resources: {}
      restartPolicy: Always
status: {}
