apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-komp.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-komp.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: registry
    spec:
      containers:
        - env:
            - name: connectionInfo_password
              value: --
            - name: connectionInfo_uri
              value: --
            - name: connectionInfo_username
              value: postgres
          image: bindock/registry-es:TAG
          name: registry
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
