apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-komp.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: registration-api
  name: registration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registration-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-komp.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: registration-api
    spec:
      containers:
        - env:
            - name: AUTH_PRIVATE_KEY
              value: |
                -----BEGIN RSA PRIVATE KEY-----
                
                -----END RSA PRIVATE KEY-----
            - name: AUTH_PUBLIC_KEY
              value: |
                -----BEGIN PUBLIC KEY-----
               
                -----END PUBLIC KEY-----
            - name: CACHE_TTL
              value: "60"
            - name: DB_HOST
              value: jsi-pg.c47qvcjxjdo1.us-east-1.rds.amazonaws.com
            - name: DB_PASSWORD
              value: uhAer5489
            - name: DB_NAME
              value: divoc
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KEYCLOAK_URL
              value: http://keycloak:8080/auth
            - name: REDIS_URL
              value: redis://redis:6379
            - name: REGISTRY_URL
              value: http://registry-es:8081
            - name: REGISTRY_WITH_ES_URL
              value: http://registry-es:8081
          image: bindock/registration_api:TAG
          name: registration-api
          ports:
            - containerPort: 8002
          resources: {}
      restartPolicy: Always
status: {}
